# Generated by Django 3.1.5 on 2021-04-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image_link',
            field=models.CharField(default='dsdsads', max_length=255, verbose_name='Link to image'),
            preserve_default=False,
        ),
    ]
