# Generated by Django 3.1.5 on 2021-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_work_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='link',
            new_name='demo_link',
        ),
        migrations.AddField(
            model_name='work',
            name='source_link',
            field=models.CharField(default='https://github.com/ruschakartur2', max_length=255, verbose_name='Link to source code'),
            preserve_default=False,
        ),
    ]
