# Generated by Django 3.1.5 on 2021-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210422_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image_link',
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default='ds', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='demo_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link to project'),
        ),
        migrations.AlterField(
            model_name='work',
            name='source_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link to source code'),
        ),
    ]
